---
"$schema": https://json-schema.org/draft/2020-12/schema
title: Product
description: Detector config file schema
type: object
"$defs":
  nonneginteger:
    type: integer
    minimum: 0
  posinteger:
    type: integer
    minimum: 1
  nonnegnumber:
    type: number
    minimum: 0.0
  posnumber:
    type: number
    exclusiveMinimum: 0.0
  posivec2:
    type: array
    minItems: 2
    maxItems: 2
    items:
      "$ref": "#/$defs/posinteger"
  nonnegvec2:
    type: array
    minItems: 2
    maxItems: 2
    items:
      "$ref": "#/$defs/nonnegnumber"
  posvec2:
    type: array
    minItems: 2
    maxItems: 2
    items:
      "$ref": "#/$defs/posnumber"
  nonnegvec4:
    type: array
    minItems: 4
    maxItems: 4
    items:
      "$ref": "#/$defs/nonnegnumber"
  matrix3x3:
    type: array
    minItems: 3
    maxItems: 3
    items:
      type: array
      minItems: 3
      maxItems: 3
      items:
        type: number
  matrix4x2:
    type: array
    minItems: 4
    maxItems: 4
    items:
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
  rotation:
    type: integer
    enum: [ 0, 90, 180, 270 ]
properties:
  camera:
    type: object
    properties:
      id:
        "$ref": "#/$defs/nonneginteger"
      size:
        "$ref": "#/$defs/posivec2"
      fourcc:
        type: string
      calibration:
        type: object
        properties:
          matrix:
            "$ref": "#/$defs/matrix3x3"
            default: [ [ 1, 0, 0 ], [ 0, 1, 0 ],  [ 0, 0, 1 ] ]
          distortion:
            type: array
            minItems: 5
            maxItems: 5
            items:
              type: number
            default: [ 0, 0, 0, 0, 0 ]
        required: [ matrix, distortion ]
        default: { }
      filename:
        type: string
      rotate:
        "$ref": "#/$defs/rotation"
        default: 0
      flipV:
        type: boolean
        default: false
      flipH:
        type: boolean
        default: false
      exposure:
        "$ref": "#/$defs/posnumber"
      smooth:
        "$ref": "#/$defs/nonnegnumber"
        default: 0.0
    default: { }
    anyOf:
      - { required: [ id ] }
      - { required: [ filename ] }
  dimensions:
    type: object
    properties:
      grid:
        "$ref": "#/$defs/posivec2"
      tile:
        "$ref": "#/$defs/posivec2"
      roi:
        "$ref": "#/$defs/matrix4x2"
        default: [ [ 0, 0 ], [ 1, 0 ], [ 1, 1 ], [ 0, 1 ] ]
      gap:
        "$ref": "#/$defs/nonnegvec2"
        default: [ 0, 0 ]
      crop:
        oneOf:
          - "$ref": "#/$defs/nonnegnumber"
          - "$ref": "#/$defs/nonnegvec2"
        default: 0.75
        title: Keep this fraction of the center part of each tile's pixel's area.
    required: [ grid, tile ]
    default: { }
  tags:
    type: object
    patternProperties:
      ^unknown$: { }
      ^[01]+$: { }
    additionalProperties: false
    required: [ unknown ]
    default:
      unknown: -1
  notify:
    type: object
    properties:
      template:
        default: [ ]
      assignTo:
        type: string
        format: json-pointer
        default: ""
      rotate:
        "$ref": "#/$defs/rotation"
        default: 0
      flipV:
        type: boolean
        default: false
      flipH:
        type: boolean
        default: false
      stdout:
        type: boolean
        default: true
      stderr:
        type: boolean
        default: false
      remote:
        type: boolean
        default: false
      url:
        type: string
      repeat:
        type: boolean
        default: false
      interval:
        title: Interval at which notification are repeated in seconds.
        "$ref": "#/$defs/posinteger"
    default: { }
    allOf:
      - if:
          properties:
            remote:
              const: true
        then:
          required: [ url ]
      - if:
          properties:
            repeat:
              const: true
        then:
          required: [ interval ]
default: { }
